#!/bin/bash

project=$1
deployment=$2
ref=$3

root=$HOME/apps/$project/$deployment

mkdir -p $root
cd $root

if [ ! -d .git ]; then
	git init
	git remote add origin $HOME/git/$project.git
fi

git fetch

if [[ -z $(git branch --list $ref) ]]; then
	git checkout -b $ref origin/$ref
else
	git checkout $ref
fi
