#!/bin/bash

name=$1
project=$2
deployment=$3

hook=./deploy/hooks/remote/$name

if [ -f $hook ]; then
	bash $hook $project $deployment
elif [ -f $hook.js ]; then
	node $hook.js $project $deployment
fi
